# Generated by Django 6.0.5 on 2026-05-31 19:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique text identifier for this cron check.', max_length=128, unique=True, verbose_name='slug')),
                ('schedule_type', models.CharField(choices=[('crontab', 'Crontab')], default='crontab', help_text='Type of scheduling mechanism used for this cron.', max_length=16, verbose_name='schedule type')),
                ('schedule', models.CharField(help_text="Schedule representation. For crontab this must be a valid crontab expression (e.g. '*/5 * * * *').", max_length=256, verbose_name='schedule')),
                ('timezone', models.CharField(blank=True, default='', help_text='Timezone for this schedule. Leave empty to use the Django default timezone.', max_length=64, verbose_name='timezone')),
                ('checkin_margin', models.DurationField(help_text='Maximum allowed delay before a check-in is considered missed.', verbose_name='check-in margin')),
                ('max_runtime', models.DurationField(help_text='Maximum expected runtime for the associated task.', verbose_name='max runtime')),
                ('failure_issue_threshold', models.PositiveIntegerField(default=2, help_text='Number of consecutive missed check-ins required to consider this cron as failed.', verbose_name='failure issue threshold')),
                ('recovery_threshold', models.PositiveIntegerField(default=1, help_text='Number of successful check-ins after a failure required to consider this cron back on track.', verbose_name='recovery threshold')),
            ],
            options={
                'verbose_name': 'cron',
                'verbose_name_plural': 'crons',
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Unique textual reference for this control.', max_length=128, unique=True, verbose_name='slug')),
                ('title', models.CharField(help_text='Human-readable title for this control.', max_length=256, verbose_name='title')),
                ('app_label', models.CharField(help_text='Django app label that discovered this control.', max_length=128, verbose_name='app label')),
                ('description', models.TextField(blank=True, default='', help_text='Full markdown description and operational manual for this control — explains what is checked and what to do on failure.', verbose_name='description')),
                ('active', models.BooleanField(default=True, help_text='Whether this control is still discovered by the registry.', verbose_name='active')),
                ('depends_on', models.ManyToManyField(blank=True, help_text='Other controls that this control depends on. If a dependency fails, this control is considered affected.', to='whealth.control', verbose_name='depends on')),
            ],
            options={
                'verbose_name': 'control',
                'verbose_name_plural': 'controls',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start', models.DateTimeField(help_text='Timestamp of when this check-in started.', verbose_name='start')),
                ('end', models.DateTimeField(blank=True, help_text='Timestamp of when this check-in ended. Null while still running.', null=True, verbose_name='end')),
                ('state', models.CharField(choices=[('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed')], default='started', help_text='Current state of this check-in.', max_length=16, verbose_name='state')),
                ('cron', models.ForeignKey(help_text='Cron check that this check-in belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='whealth.cron', verbose_name='cron')),
            ],
            options={
                'verbose_name': 'check-in',
                'verbose_name_plural': 'check-ins',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(help_text='Timestamp when this incident started.', verbose_name='date start')),
                ('date_ignored', models.DateTimeField(blank=True, help_text='Timestamp when this incident was last ignored. Null if never ignored or still active.', null=True, verbose_name='date ignored')),
                ('date_end', models.DateTimeField(blank=True, help_text='Timestamp when this incident ended. Null while still active.', null=True, verbose_name='date end')),
                ('key', models.CharField(help_text='Instance key for this incident. A (control, key) tuple uniquely identifies an open incident — the same control can fail on different instances concurrently.', max_length=256, verbose_name='key')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Opaque JSON-serializable value providing context about what caused this incident.', verbose_name='context')),
                ('control', models.ForeignKey(help_text='Control associated with this incident.', on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='whealth.control', verbose_name='control')),
            ],
            options={
                'verbose_name': 'incident',
                'verbose_name_plural': 'incidents',
                'constraints': [models.UniqueConstraint(condition=models.Q(('date_end__isnull', True)), fields=('control', 'key', 'date_end'), name='unique_open_incident', violation_error_message='An open incident already exists for this control and key.')],
            },
        ),
    ]
