# Generated by Django 6.0.5 on 2026-05-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whealth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Opaque JSON-serializable value providing context about what caused this incident.', verbose_name='context'),
        ),
    ]
