# Generated by Django 6.0.5 on 2026-06-29 13:45

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whealth", "0002_runrecord_whealth_run_date_en_27f136_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runrecord",
            name="duration",
        ),
        migrations.AddField(
            model_name="runrecord",
            name="duration",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("date_end"), "-", models.F("date_start")
                ),
                output_field=models.DurationField(
                    blank=True,
                    help_text="Wall-clock duration of this run.",
                    null=True,
                    verbose_name="duration",
                ),
            ),
        ),
    ]
