# Generated by opencode

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whealth", "0002_alter_incident_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="control",
            name="active",
            field=models.BooleanField(
                default=True,
                help_text="Whether this control is still discovered by the registry.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="control",
            name="app_label",
            field=models.CharField(
                default="",
                help_text="Django app label that discovered this control.",
                max_length=128,
                verbose_name="app label",
            ),
            preserve_default=False,
        ),
    ]
