# Generated by Django 6.0.5 on 2026-05-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whealth', '0003_control_active_control_app_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='date_ignored',
            field=models.DateTimeField(blank=True, help_text='Timestamp when this incident was last ignored. Null if never ignored or still active.', null=True, verbose_name='date ignored'),
        ),
    ]
