# Generated by Django 6.0.5 on 2026-05-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique key for this value.', max_length=128, unique=True, verbose_name='key')),
                ('value', models.TextField(blank=True, default='', help_text='Arbitrary value associated with this key.', verbose_name='value')),
            ],
            options={
                'verbose_name': 'key value',
                'verbose_name_plural': 'key values',
            },
        ),
    ]
